### ISSUE TITLE
Marker colors

### ISSUE THREAD

**Issue by GHXST01** [rafpyprog/pymaps#1]
Hey Rafael,

Awesome wrapper you have made. I really dig it. Currently there's no customization option for marker colors though. I think it would be really nice if we could add individual colors to markers just like we can add labels for example.

Are you working on this already, or do you want me to try to add that and submit it?

**Comment by GHXST01** [comment]
I found out that the current marker used is an actual image, meaning that we won't be able to change it's color with some simple CSS unfortunately.

However I did some digging around and came up with a decent way to achieve what I wanted.
I attached the function below, let me know what you think.

```
def colored_icon(color, scale=1):
    """ Returns colored marker """

    if color == 'GREY':
        color = '7495a6'

    if color == 'GREEN':
        color = '4db546'

    if color == 'RED':
        color = 'db4437'

    icon_url = ('https://www.google.com/maps/vt/icon/name='
                'assets/icons/poi/tactile/pinlet_shadow-1-small.png,'
                'assets/icons/poi/tactile/pinlet_outline_v2-1-small.png,'
                'assets/icons/poi/tactile/pinlet-1-small.png,'
                'assets/icons/poi/quantum/pinlet/dot_pinlet-1-small.png&'
                'highlight=ff000000,ffffff,{color},ffffff&color=ff000000?'
                'scale={scale}').format(color=color, scale=str(scale))

    return icon_url
```

Preview of the result:
![](https://i.imgur.com/qnTmKCS.png)

**Comment by rafpyprog** [comment]
Hi GHXST01,

Great suggestion! I will implent it. However, instead of using the set of
icons you suggested I prefer to use custom versions of the standard icon:
https://www.google.com/maps/vt/icon/name=assets/icons/spotlight/spotlight_pin_v2_shadow-1-small.png,assets/icons/spotlight/spotlight_pin_v2-1-small.png,assets/icons/spotlight/spotlight_pin_v2_dot-1-small.png,assets/icons/spotlight/spotlight_pin_v2_accent-1-small.png&highlight=FF00FF,FF00FF,960a0a,FF00FF&color=FF00FF?scale=3

I will also add an option for the icon size (small , medium, big) using the
scale parameter of the URLs you've found.

Thanks very much for contributing!





*Atenciosamente,Rafael A. Ribeiro*
*(61**) 998.191.600*

As informações contidas nesta mensagem e nos arquivos anexados são para uso
exclusivo do destinatário aqui indicado e podem conter assuntos comerciais,
de propriedade intelectual ou outras informações confidenciais, protegidas
pelas leis aplicáveis.

Caso não seja o destinatário correto, por favor, notifique o remetente
imediatamente e elimine esta mensagem, uma vez que qualquer revisão,
leitura, cópia e, ou divulgação do conteúdo desta mensagem é estritamente
proibido e não autorizado.

Obrigado por sua cooperação.

2018-02-24 13:45 GMT-03:00 GHXST01 <notifications@github.com>:
